[project]
name = "morsaik"
version = "0.1.0"
authors = [
    { name="Johannes Harth-Kitzerow", email="jharthki@mpa-garching.mpg.de" },
]
description = "Sequence Motif Reactor Simulation, Analysis and Inference Kit."
readme = "README.rst"
requires-python = ">=3.10,<4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "scipy >= 1.15.3",
    "nifty8>=8.5",
    "jax",
    "jaxlib",
    "matplotlib",
    "units>=0.07",
    "diffrax==0.7.0",
    "sphinx (>=8.1.3,<9.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "myst-parser (>=4.0.0,<5.0.0)",
    "pydata-sphinx-theme (>=0.16.1,<0.17.0)"
]
license = "GPL-3.0-or-later"

[project.optional-dependencies]
doc = [
    "sphinx",
    "pyyaml",
    "myst_parser",
    "pydata-sphinx-theme",
]

[poetry.group.dev.dependencies]
pytest = "8.2.2"

[build-system]
requires = ["setuptools>=65.7.0",
    "scipy >= 1.15.3",
    "nifty8>=8.5",
    "jax",
    "jaxlib",
    "matplotlib",
    "units>=0.07",
    "pyyaml==6.0.1",
    "diffrax==0.7.0"
    ]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/joharkit/morsaik"
Issues = "https://github.com/joharkit/morsaik/issues"
